name: Release Docker Image

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  IMAGE_NAME: yearmaps

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: patrick91/setup-python@99a5f2b0ed0ad8a829212e44012c5116ef2598ee
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install Node dependencies
        run: yarn install
        working-directory: frontend

      - name: Build the frontend
        run: yarn build
        working-directory: frontend

      - name: Build package
        run: poetry build

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@master

      - name: Log into Dockerhub
        uses: docker/login-action@master
        with:
          username: zxilly
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into GitHub
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          images: zxilly/${{ env.IMAGE_NAME }},ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}