name: Build Production

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  IMAGE_NAME: yearmaps

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: patrick91/setup-python@99a5f2b0ed0ad8a829212e44012c5116ef2598ee
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@latest

      - name: Log into registry
        uses: docker/login-action@latest
        with:
          username: zxilly
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@latest
        with:
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
          images: zxilly/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@latest
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}