name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: patrick91/setup-python@99a5f2b0ed0ad8a829212e44012c5116ef2598ee
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Analysing the code with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')
